name: motor_impairment_neural_disorders
channels:
  - defaults
dependencies:
  - python>=3.6
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas>=0.18
  - scikit-learn
  - pip:
    # environs
    - environs==8.0.0
    # Pathlib
    - pathlib==1.0.1
    # Dependency injection microframework for Python
    - dependency-injector==3.23.2
    # PyYAML
    - PyYAML==5.3.1
    # PyWavelets
    - PyWavelets==1.1.1
    # Tensorflow
    - tensorflow==2.3.0
